services:
  referral-db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'referral'
      MYSQL_USER: 'referral'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password12345'
    volumes:
      - my-db:/var/lib/mysql
  refferal:
    build:
      context: ./referral
    depends_on:
        - referral-db
    ports:
      - 30002:5001
# Names our volume
volumes:
  my-db: